brew 'zsh'

cask '1password'
cask 'alfred'
cask 'brave-browser'
cask 'calibre'
cask 'clockify'
cask 'dropbox'
cask 'evernote'
cask 'fujitsu-scansnap-home'
cask 'gimp'
cask 'google-drive'
cask 'miro'
cask 'nordvpn'
cask 'notion'
cask 'readdle-spark'
cask 'signal'
cask 'rectangle'
cask 'spotify'
cask 'telegram'

# Not installable through brew:
# craft
